server:
  port: 8082

url:
  openCageApiUrl: https://api.opencagedata.com/geocode/v1/json?q=
  pretty: pretty=1
  weatherAppApiUrl: http://localhost:8081/weather/
  urlOverHttps: https://localhost:8445/check-token

key:
  openCageApiKey: e696e04572d344d4b1191de598cd0a75

spring:
  application:
    name: extreme-events