spring:
  profiles:
    dev
  data:
    mongodb:
      database: extremeevents
      uri: mongodb://localhost:27017/extremeevents
      admin: extremeevents
      password: lucratorcomputer

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/